### PR TITLE
add scalafix-named-literal-arguments

### PR DESCRIPTION
**Pull request by bjaglin**

### CODE REVIEW

**Review by ckipp01 — COMMENTED** [review]
Thanks for the pr @bjaglin! Just to be sure, will Steward correctly find the build file here since there is no top level build file? Or do you have to use a local steward conf defining the `buildRoots` to be `scalafix` for it to work? We can also just merge, see if it works, and then adjust if necessary.

**Comment by bjaglin** [comment]
> We can also just merge, see if it works, and then adjust if necessary.

That's what I had in mind, thanks for checking!

**Review by ckipp01 — APPROVED** [review]

**Comment by ckipp01** [comment]
> > We can also just merge, see if it works, and then adjust if necessary.
> 
> That's what I had in mind, thanks for checking!

Sounds good. I'll merge and manually trigger this so we'll see right away if it works or not.

**Comment by ckipp01** [comment]
Looking at the logs I'm seeing:

```
  2023-06-06 07:17:51,468 INFO  Check cache of scalacenter/scalafix-named-literal-arguments
  2023-06-06 07:17:51,698 INFO  Clone scalacenter/scalafix-named-literal-arguments
  2023-06-06 07:17:51,920 INFO  Refresh cache of scalacenter/scalafix-named-literal-arguments
  2023-06-06 07:17:51,929 INFO  Get dependencies in . from sbt
  2023-06-06 07:18:05,448 INFO  Find updates for scalacenter/scalafix-named-literal-arguments
  2023-06-06 07:18:05,448 INFO  Found 0 updates
```
Were you expecting any updates? I can't tell if `Get dependencies in . from sbt` means it was _only_ looking in `.` or if it traversed or not.

**Comment by bjaglin** [comment]
I have added https://github.com/scalacenter/scalafix-named-literal-arguments/commit/080f0b4cfa687c7df8daee02d73019e583fde304, could you retrigger the workflow to see if it helps?

**Comment by ckipp01** [comment]
> I have added [scalacenter/scalafix-named-literal-arguments@080f0b4](https://github.com/scalacenter/scalafix-named-literal-arguments/commit/080f0b4cfa687c7df8daee02d73019e583fde304), could you retrigger the workflow to see if it helps?

Looks like that did the trick!

**Pull request merged**
